### ISSUE TITLE
The notification modal not clearing previous notifications.

### ISSUE THREAD

**Issue by nadeem09wani** [G33kzD3n/locate_mobile#23]
[9af13ffc](https://github.com/G33kzD3n/locate_mobile/commit/9af13ffc0ea3a20bda1599d4e793e35b1dc55144)
When i updated the bus status continuously to 10 or more , the clear button in notification modal hides somehow, please see to it.
Also and you need to check , when i am _logged in_  in as coordinator_ in one instance, and someone on diff side _logged in_ as **student** both belonging to same bus say 8840, notifications of coordinator must not been available on students notification modal.

> Scenario : Driver of 8840 pushes breakdown , only the coordinator 's notification modal should receive this notification msg.

**Comment by muftisamiullah** [comment]
We need to create separate socket channels for that..this is a test version showing how the notifications will work.

**Comment by muftisamiullah** [comment]
Modal clear notifications that are less than 10..it hides the clear button bcz modal doesnt have a scroll controller..i wil implement the scroll in it soon
